### ISSUE TITLE
Grav needs PHP v5.5.9

### ISSUE THREAD

**Issue by ajbozdar** [gautamkrishnar/grav-openshift-quickstart#3]
Grav is not working on OpenShift as it needs minimum PHP v5.5.9.

**Comment by gautamkrishnar** [comment]
yes its mentioned in #1 i need someone's help with this

**Comment by ajbozdar** [comment]
What help do you need?

**Comment by gautamkrishnar** [comment]
@bozj  i am not sure about how to implement a custom PHP version on openshift. If you know how to implement it, Please open a pull request.

**Comment by ajbozdar** [comment]
OpenShift and Grav both have introduced significant changes in past two years. The issue is no more applicable to new environments and workflows, i.e., I am closing it now.
